apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldump
  namespace: exercise-02
  labels:
    app: mysqldump
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
