apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-pvc
  namespace: exercise-01
  labels:
    app: drupal
    type: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
