## Global Docker image registry
## Please, note that this will override the image registry for all the images, including dependencies, configured to use the global value
##
# global:
#   imageRegistry:

## Bitnami WordPress image version
## ref: https://hub.docker.com/r/bitnami/wordpress/tags/
##
namespace: exercise-01
image:
  registry: docker.io
  repository: bitnami/wordpress
  tag: 4.9.8-debian-9-r51
  pullPolicy: IfNotPresent
########
wordpressUsername: JiuJitsu
wordpressEmail: user@example.com
wordpressFirstName: Pablo
wordpressLastName: Lara
wordpressBlogName: JiuJitsu Chart for WP =D
wordpressTablePrefix: wp_
allowEmptyPassword: true
replicaCount: 1
#########
wordpressDatabaseName: bitnami_wordpress
wordpressDatabaseUser: bn_wordpress
wordpressDatabasePassword: bitnami
wordpressPassword: bjjtimes
mariadbRootUser: root
mariadbRootPassword: root
########
mariadb:
  enabled: true
  replication:
    enabled: false
  db:
    name: bitnami_wordpress
    user: bn_wordpress
    password: bitnami
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
########
mysql:
  enabled: false
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
########
serviceType: LoadBalancer
########
mysqldump:
  enabled: true
  everyMinutes: 60
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
#######
## Allow health checks to be pointed at the https port
healthcheckHttps: false
## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes)
livenessProbe:
  initialDelaySeconds: 160
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
## Configure the ingress resource that allows you to access the
## Wordpress installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
################
ingress:
  enabled: true
  hosts:
  - name: myblog.com
    tls: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
##############
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
##########
resources:
  requests:
    memory: 512Mi
    cpu: 300m
nodeSelector: {}
################
networkpolicies:
  enable: true
################
