apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-master-config-cm
  namespace: exercise-03
  labels:
    app: wordpress
    tier: backend
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/bitnami/mariadb
    port=3306
    socket=/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=0.0.0.0
    pid-file=/bitnami/mariadb/tmp/mysqld.pid
    log-error=/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
     [client]
    port=3306
    socket=/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

    [manager]
    port=3306
    socket=/bitnami/mariadb/tmp/mysql.sock
    pid-file=/bitnami/mariadb/tmp/mysqld.pid
