apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: exercise-01
  labels:
    app: wordpress
    tier: backend
spec:
  type: ClusterIP
  ports:
  - name: mysql-port
    port: 3306
  selector:
    app: wordpress
    tier: backend
